// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export default {
    "graphqlEndpoint": "https://cc-api.code4chiba.org/graphql",
    "region": "ap-northeast-1",
    "authenticationType": "API_KEY",
    "apiKey": "[ここにAPIキーを入力する]"
}
